NewsPaper/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    #path('news/', include('news.urls')),  не удалил на случай изменений в будущем
    path('', include('news.urls')),
    path('auth/', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    #path('appointment/', include('appointment.urls')),
    path('appointments/', include(('appointment.urls', 'appointments'), namespace='appointments')),
    ]

appointment/urls.py
from django.urls import path
from .views import AppointmentView

urlpatterns = [
    path('make_appointment', AppointmentView.as_view(), name='make_appointment')
    ]

news/urls.py
from django.urls import path
from .views import PostsList, PostDetail, Posts_search, PostCreate,  PostDelete, PostUpdate, IndexView
from .views import upgrade_me, subscribe

urlpatterns = [
    path('news/', PostsList.as_view(), name='news'),
    #path('', PostsList.as_view()), не удалил на случай изменений в будущем
    path('news/<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('search/', Posts_search.as_view(), name='Posts_search'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('<int:pk>/create/', PostUpdate.as_view(), name='post_update'),
    path('', IndexView.as_view()),
    path('upgrade/', upgrade_me, name='upgrade'),
    path('subscriptions/', subscribe, name='subscriptions'),
    ]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_rate = models.IntegerField(default=0)

    def update_rating(self):
        # суммарный рейтинг всех комментариев к статьям
        sum_rating = self.post_set.aggregate(post_rating=Sum('post_rate'))
        result_sum_rating = 0
        try:
            result_sum_rating += sum_rating.get('post_rating')
        except TypeError:
            result_sum_rating = 0

        # суммарный рейтинг всех комментариев самого автора
        sum_comment_rating = self.user.comment_set.aggregate(comment_rating=Sum('comment_rate'))
        result_sum_comment_rating = 0
        result_sum_comment_rating += sum_comment_rating.get('comment_rating')

        # суммарный рейтинг каждой статьи автора умноженный на 3
        self.user_rate = result_sum_rating * 3 + result_sum_comment_rating
        # сохраняем результаты в базу данных
        self.save()

    def __str__(self):
        return f'{self.user}. Рейтинг: {self.user_rate}'


class Category(models.Model):
    name_category = models.CharField(max_length=52, unique=True)
    subscribers = models.ManyToManyField(User, null=True, through='CategoryUser')

    # def __str__(self):
    #   return f'Категория {self.name_category}'

    def get_subscribers_emails(self):
        result = set()
        for user in self.subscribers.all():
            result.add(user.email)
        return result
        # subscribers = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscribed_categories')
    # модуль D9


class CategoryUser(models.Model):  # от Станислава
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Post(models.Model):
    post = models.ForeignKey(Author, on_delete=models.CASCADE)  # связь «один ко многим» с моделью Author;

    created = models.DateTimeField(auto_now_add=True)  # автоматически добавляемая дата и время создания;

    #Post = models.ManyToManyField(Category, through='PostCategory')  # связь «многие ко многим» с моделью Category
    # (с дополнительной моделью PostCategory);
    Post = models.ManyToManyField(Category, through='PostCategory') # заменил название переменной

    title = models.CharField(max_length=150)  # заголовок статьи/новости;

    text = models.TextField()  # текст статьи/новости;

    post_rate = models.IntegerField(default=0)  # рейтинг статьи/новости.

    def __str__(self):
        return f'{self.title()}: {self.text[:20]}'

    def get_absolute_url(self):
        return f'/news/{self.id}'

    article = 'AR'
    news = 'NE'

    posts = [
        (article, 'Статья'),
        (news, 'Новость')
    ]
    choice = models.CharField(max_length=2,  # поле с выбором — «статья» или «новость»;
                              choices=posts,
                              default=news)

    def like(self):
        self.post_rate += 1
        self.save()

    def dislike(self):
        self.post_rate -= 1
        self.save()

    def preview(self):
        size = 124 if len(self.text) > 124 else len(self.text)
        return self.text[:size] + '...'


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)  # связь «один ко многим» с моделью Post
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    comment_rate = models.IntegerField(default=0)

    def like(self):
        self.comment_rate += 1
        self.save()

    def dislike(self):
        self.comment_rate -= 1
        self.save()


class BasicSignupForm(SignupForm):

    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        common_group = Group.objects.get(name='common')
        common_group.user_set.add(user)
        return user

templates/base.html
from django.contrib import admin

<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

templates/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}
            {% endblock title %}</title>

        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                    {% block menu_bar %}
                <a class="navbar-brand" href="{% url 'Posts_search'%}"> Найти статью  </a>
                <a class="navbar-brand" href="{% url 'post_create'%}"> Создать статью  </a>
                <a class="navbar-brand" href="{% url 'news'%}"> Список новостей  </a>
                    {% endblock menu_bar %}

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Home</a></li>

                        {% block sign %}

                        {% if request.user.is_authenticated %}
                        <li class="nav-item"> <a class="nav-link active" href="{% url 'logout' %}">Выход</a></li>
                         <li class="nav-item"> <a class="nav-link active" href="{% url 'subscriptions' %}">Подписки</a></li>
                        {% else %}
                        <li class="nav-item"> <a class="nav-link active" href="/accounts/login/">Вход</a></li>
                        {% endif %}
                        {% endblock  %}

                        <li class="nav-item dropdown">
<!--                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>-->
<!--                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">-->
<!--                                <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--                                <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--                                <li><hr class="dropdown-divider" /></li>-->
<!--                                <li><a class="dropdown-item" href="#">Something else here</a></li>-->
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                <h4>
                    {% block page_title %}
                    {% endblock page_title %}
                </h4>
                {% block content %}
                {{flatpage.content}}
                {%endblock content %}

            </div>
        </div>

    </body>
</html>

templates/index.html
{% extends "main.html" %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<div> Здесь может содержаться персональная информация для каждого пользователя </div>

{% if is_not_author %}
<button> <a href="upgrade/"> Стать автором</a> </button>
{% endif %}
<button> <a href="logout/">Выйти</a> </button>

{% endblock %}

templates/login.html
{% extends "main.html" %}

{% block content %}
<h2> Войти в систему </h2>
<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Войти">
</form>
<button> <a href="/signup"> Регистрация </a></button>
{% endblock %}

templates/logout.html
{% extends "main.html" %}

{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/make_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Make an appointment</title>
</head>
<body>
    <h1>Make an appointment</h1>
    <form action="{% url 'appointments:make_appointment' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="client_name">Your name</label>
        <input type="text" name="client_name"><br>
        <label for="message">Short description of your issue</label>
        <input type="text" name="message"><br>
        <label for="date">Choose time</label>
        <input type="date" name="date"><br>
        <input type="submit">
    </form>
</body>
</html>

templates/signup.html
{% extends "main.html" %}

{% block content %}
<h2> Войти в систему </h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Продолжить">
</form>
{% endblock %}

templates/subscribe.html
{% extends "default.html" %}


{% block title %}
подписка на новости
{% endblock title %}


{% block page_title %}



{% if subscribed %}
Вы подписаны на  новости из разделов:

<form method="POST" action="{% url 'subscriptions' %}">
     <input type="hidden" name ='from'  value="subscribe.html" >
    {% csrf_token %}
<table>
    {% for cat in request.user.category_set.all %}
    <tr>
<!--        <td> {{cat.name}} </td>-->
<!--        <td> <input type="submit" name ='{{cat.id}}'  value="отписаться" > </td>-->

        <td> {{cat.name}} </td>

        <td> <button type="submit"  name="category" value="{{cat.id}}" >отписаться</button></td>
    </tr>
    {% endfor %}
</table>
    </form>

{% else %}
У вас нет активных подписок
{% endif %}

{% endblock page_title %}


{% block content %}
{% endblock content %}